services:
  api:
      build: .
      container_name: DjangoAPI
      command: >
        bash -c "python manage.py collectstatic --no-input &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 200 --workers=5"
      # ports:
      #   - 8000:8000
      restart: always
      depends_on:
        - db
      volumes:
        - .:/code
        - static_volume:/code/static/
        - media_volume:/code/media/
      env_file:
        - ./.env/.env.dev
      networks:
        api_network:

  # PostgreSQL Database Service
  db:
    container_name: PostgreSQL
    image: postgres:16.2-alpine
    expose:
      - 5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/.env.prod
    networks:
      api_network:

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/.well-known/acme-challenge/
      - static_volume:/code/static/
      - media_volume:/code/media/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    env_file:
      - ./.env/.env.prod
    networks:
      api_network:


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot 
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot-path /var/www/certbot; sleep 5d & wait $${!}; done;'"
    env_file:
      - ./.env/.env.prod

  
volumes:
  # will be used to store our ssl certificate and make it persistent as wel   
  static_volume:
  media_volume:
  postgres_data:
  certbot_conf:
  certbot_www:
    
networks:
  api_network: