services:
  api:
      build: .
      container_name: DjangoAPI
      command: >
        bash -c "python manage.py collectstatic --no-input &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 200 --workers=5"
      # ports:
      #   - 8000:8000
      restart: always
      depends_on:
        - db
      volumes:
        - .:/code
        - static_volume:/code/static/
        - media_volume:/code/media/
      env_file:
        - ./.env/.env.prod
      networks:
        api_network:

  # PostgreSQL Database Service
  db:
    container_name: PostgreSQL
    image: postgres:16.2-alpine
    expose:
      - 5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/.env.prod
    networks:
      api_network:

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx_prod.conf:/etc/nginx/nginx_prod.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot/
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    env_file:
      - ./.env/.env.prod
    networks:
      api_network:


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot/
    env_file:
      - ./.env/.env.prod

  
volumes:
  # will be used to store our ssl certificate and make it persistent as wel   
  static_volume:
  media_volume:
  postgres_data:
  certbot_www:
    
networks:
  api_network:
