# Generated by Django 4.2.9 on 2024-02-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_variationcategory_variation_values"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItemVariations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "variation_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.variationcategory",
                    ),
                ),
                ("variation_value", models.ManyToManyField(to="store.variationvalue")),
            ],
            options={
                "verbose_name": "CartItem variation",
                "verbose_name_plural": "CartItem variations",
                "db_table": "Cart_item_variation",
            },
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="carts.cartitemvariations"),
        ),
    ]
