# Generated by Django 4.2.9 on 2024-02-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="VariationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("variation_values", models.ManyToManyField(to="store.variationvalue")),
            ],
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.variationcategory",
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.variationvalue"
            ),
        ),
    ]
