# Generated by Django 4.2.9 on 2024-02-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variationvalue_variationcategory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variation",
            options={"verbose_name": "Variation", "verbose_name_plural": "Variations"},
        ),
        migrations.AlterModelOptions(
            name="variationcategory",
            options={
                "verbose_name": "Variation category",
                "verbose_name_plural": "Variation categories",
            },
        ),
        migrations.AlterModelOptions(
            name="variationvalue",
            options={
                "verbose_name": "Variation value",
                "verbose_name_plural": "Variation values",
            },
        ),
        migrations.RemoveField(
            model_name="variation",
            name="variation_value",
        ),
        migrations.AlterModelTable(
            name="variationcategory",
            table="Variation_category",
        ),
        migrations.AlterModelTable(
            name="variationvalue",
            table="Variation_value",
        ),
        migrations.AddField(
            model_name="variation",
            name="variation_value",
            field=models.ManyToManyField(to="store.variationvalue"),
        ),
    ]
