# Generated by Django 4.2.9 on 2024-03-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productvariations_delete_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
