# Generated by Django 4.2.9 on 2024-02-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="stoc",
        ),
    ]
