# Generated by Django 4.2.9 on 2024-02-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_variation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variationcategory",
            name="variation_values",
        ),
    ]
