# Generated by Django 4.2.9 on 2024-03-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariations",
            name="variation_category",
        ),
        migrations.RemoveField(
            model_name="productvariations",
            name="variation_value",
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.variationcategory",
                    ),
                ),
                (
                    "variation_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.variationvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variation",
                "verbose_name_plural": "Variations",
                "db_table": "Variation",
            },
        ),
        migrations.AddField(
            model_name="productvariations",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
