# Generated by Django 4.2.9 on 2024-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_price_productvariations_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariations",
            options={
                "verbose_name": "Product_variation",
                "verbose_name_plural": "Product variations",
            },
        ),
        migrations.AlterModelOptions(
            name="variationcategory",
            options={
                "verbose_name": "Variation_category",
                "verbose_name_plural": "Variation categories",
            },
        ),
        migrations.AlterModelOptions(
            name="variationvalue",
            options={
                "verbose_name": "Variation_value",
                "verbose_name_plural": "Variation values",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name="productvariations",
            table="Product_variation",
        ),
    ]
