# Generated by Django 4.2.9 on 2024-02-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_variation_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation",
            old_name="product",
            new_name="category",
        ),
    ]
