# Generated by Django 4.2.9 on 2024-03-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "Product_gallery",
                "verbose_name_plural": "Products gallery",
            },
        ),
        migrations.AlterModelTable(
            name="productgallery",
            table="Product_gallery",
        ),
    ]
