# Generated by Django 4.2.9 on 2024-02-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_product_variation_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation",
            old_name="category",
            new_name="product",
        ),
    ]
