# Generated by Django 4.2.9 on 2024-02-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_rename_category_variation_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.product"
            ),
        ),
    ]
