# Generated by Django 4.2.9 on 2024-02-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="product_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
