# Generated by Django 4.2.9 on 2024-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("New", "New"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
